// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate() {
  return window['go']['app']['App']['Authenticate']();
}

export function ClearIdentity() {
  return window['go']['app']['App']['ClearIdentity']();
}

export function CreateIdentity() {
  return window['go']['app']['App']['CreateIdentity']();
}

export function GetAddress() {
  return window['go']['app']['App']['GetAddress']();
}

export function HasIdentity() {
  return window['go']['app']['App']['HasIdentity']();
}
