// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function Authenticate():Promise<string>;

export function ClearIdentity():Promise<void>;

export function CreateIdentity():Promise<service.Identity>;

export function GetAddress():Promise<string>;

export function HasIdentity():Promise<boolean>;
